2023-07-12 01:37:30,855 ERROR log Internal Server Error: /Postnews/ Z:\myProjectDjango\lib\site-packages\django\utils\log.py
Traceback (most recent call last):
  File "Z:\myProjectDjango\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\myProjectDjango\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "Z:\myProjectDjango\lib\site-packages\django\template\response.py", line 111, in render
    self.content = self.rendered_content
  File "Z:\myProjectDjango\lib\site-packages\django\template\response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "Z:\myProjectDjango\lib\site-packages\django\template\response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "Z:\myProjectDjango\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news_portal/post_list.html
2023-07-12 01:37:30,857 ERROR basehttp "GET /Postnews/ HTTP/1.1" 500 86286 Z:\myProjectDjango\lib\site-packages\django\core\servers\basehttp.py
2023-07-12 01:38:55,761 ERROR log Internal Server Error: /Postnews/ Z:\myProjectDjango\lib\site-packages\django\utils\log.py
Traceback (most recent call last):
  File "Z:\myProjectDjango\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\myProjectDjango\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "Z:\myProjectDjango\lib\site-packages\django\template\response.py", line 111, in render
    self.content = self.rendered_content
  File "Z:\myProjectDjango\lib\site-packages\django\template\response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "Z:\myProjectDjango\lib\site-packages\django\template\response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "Z:\myProjectDjango\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news_portal/post_list.html
2023-07-12 01:38:55,764 ERROR basehttp "GET /Postnews/ HTTP/1.1" 500 86286 Z:\myProjectDjango\lib\site-packages\django\core\servers\basehttp.py
(<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('news_portal/post_list.html'), <traceback object at 0x000001F02E542F40>) 2023-07-12 01:41:37,679 ERROR log Internal Server Error: /Postnews/ Z:\myProjectDjango\lib\site-packages\django\utils\log.py
Traceback (most recent call last):
  File "Z:\myProjectDjango\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\myProjectDjango\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "Z:\myProjectDjango\lib\site-packages\django\template\response.py", line 111, in render
    self.content = self.rendered_content
  File "Z:\myProjectDjango\lib\site-packages\django\template\response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "Z:\myProjectDjango\lib\site-packages\django\template\response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "Z:\myProjectDjango\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news_portal/post_list.html
None 2023-07-12 01:41:37,681 ERROR basehttp "GET /Postnews/ HTTP/1.1" 500 86303 Z:\myProjectDjango\lib\site-packages\django\core\servers\basehttp.py
2023-07-12 01:46:43,086 ERROR log Internal Server Error: /Postnews/ Z:\myProjectDjango\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('news_portal/post_list.html'), <traceback object at 0x000001A0715C5A40>)
Traceback (most recent call last):
  File "Z:\myProjectDjango\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "Z:\myProjectDjango\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "Z:\myProjectDjango\lib\site-packages\django\template\response.py", line 111, in render
    self.content = self.rendered_content
  File "Z:\myProjectDjango\lib\site-packages\django\template\response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "Z:\myProjectDjango\lib\site-packages\django\template\response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "Z:\myProjectDjango\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news_portal/post_list.html
2023-07-12 01:46:43,088 ERROR basehttp "GET /Postnews/ HTTP/1.1" 500 86303 Z:\myProjectDjango\lib\site-packages\django\core\servers\basehttp.py None
